# Site
repository: quazepam/pirhana
# favicon: images/favicon.ico

# Personal info
name: André Sucena
title: SAP consultant
email: andresucena@pirhanaconsulting.com
website: www.pirhanaconsulting.com

# Social links
# twitter_username: facespics
# github_username:  sproogen
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: andresucena
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hey there. My name's André and I'm a 30-something portuguese industrial engineer turned SAP consultant. I have vast experience on the supply chain on both sides of the table, so if you need a logistics guy that will add value as a bridge between the end users and the more technical people, feel free to contact me and I'll be happy to help. 

  I am most skilled in: <mark>Sales and Distribution (SD)</mark> and <mark>Materials Management (MM)</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in the supply chain and ERP systems, some of my other interests and hobbies are:
   - Hiking
   - Reading
   - Playing guitar
   - Watching old movies
   - Gaming
   - Fitness

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
